@echo off
echo Creating Virtual Environment...
python -m venv venv
echo Installing Dependencies in Venv...
.\venv\bin\python -m pip install flask flask-cors requests
echo Starting Aether...
.\venv\bin\python main.py
pause