@echo off
echo Creating Virtual Environment...
python -m venv venv
echo Installing Dependencies in Venv...
.\venv\Scripts\python -m pip install flask flask-cors requests
echo Building Frontend...
cd frontend
call npm run build
cd ..
echo Deploying Frontend...
if exist static rmdir /s /q static
xcopy frontend\dist static /E /I /Y >nul
echo Starting Aether...
.\venv\Scripts\python main.py
pause